// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: protos/orderer/sraft.proto

package orderer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SRaft_AppendShard_FullMethodName = "/orderer.sraft.SRaft/AppendShard"
)

// SRaftClient is the client API for SRaft service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SRaftClient interface {
	AppendShard(ctx context.Context, in *AppendShardRequest, opts ...grpc.CallOption) (*AppendShardResponse, error)
}

type sRaftClient struct {
	cc grpc.ClientConnInterface
}

func NewSRaftClient(cc grpc.ClientConnInterface) SRaftClient {
	return &sRaftClient{cc}
}

func (c *sRaftClient) AppendShard(ctx context.Context, in *AppendShardRequest, opts ...grpc.CallOption) (*AppendShardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendShardResponse)
	err := c.cc.Invoke(ctx, SRaft_AppendShard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SRaftServer is the server API for SRaft service.
// All implementations must embed UnimplementedSRaftServer
// for forward compatibility.
type SRaftServer interface {
	AppendShard(context.Context, *AppendShardRequest) (*AppendShardResponse, error)
	mustEmbedUnimplementedSRaftServer()
}

// UnimplementedSRaftServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSRaftServer struct{}

func (UnimplementedSRaftServer) AppendShard(context.Context, *AppendShardRequest) (*AppendShardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendShard not implemented")
}
func (UnimplementedSRaftServer) mustEmbedUnimplementedSRaftServer() {}
func (UnimplementedSRaftServer) testEmbeddedByValue()               {}

// UnsafeSRaftServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SRaftServer will
// result in compilation errors.
type UnsafeSRaftServer interface {
	mustEmbedUnimplementedSRaftServer()
}

func RegisterSRaftServer(s grpc.ServiceRegistrar, srv SRaftServer) {
	// If the following call pancis, it indicates UnimplementedSRaftServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SRaft_ServiceDesc, srv)
}

func _SRaft_AppendShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendShardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SRaftServer).AppendShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SRaft_AppendShard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SRaftServer).AppendShard(ctx, req.(*AppendShardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SRaft_ServiceDesc is the grpc.ServiceDesc for SRaft service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SRaft_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orderer.sraft.SRaft",
	HandlerType: (*SRaftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppendShard",
			Handler:    _SRaft_AppendShard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/orderer/sraft.proto",
}
